[package]
name = "print-files"
version = "0.1.0"
authors = ["mattpilla <kaztalek@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
clap = {version = "~2.33.0", features = ["yaml"]}
